### ISSUE TITLE
优化意见

### ISSUE THREAD

**Issue by FragrantRye** [TuanZ7/GA-Firefox-#1]
1. alpha通道突变时将范围限定为0-64，较低的透明度保证了更多的三角形对最终适应度有影响。
2. 坐标和颜色分开突变（不同时突变），解耦后有更大概率突变出优秀基因。
3. 三个顶点坐标解耦，横纵坐标解耦，RGBA颜色分量解耦，进一步提高突变出优秀基因的概率。
4. 以比颜色突变概率更大一些（2~3倍）的概率突变坐标，能更快收敛。

下图是我基于改进的代码用chrome图标迭代15000代后的结果，看起来比您的结果要好一些。
![第15000代最优扇贝](https://user-images.githubusercontent.com/22676175/73603207-9dafd000-45ba-11ea-8d56-591e5c4c76c1.png)

**Comment by FragrantRye** [comment]
用QQ图标，150个三角形，迭代32000代的结果：
![第32000代最优扇贝](https://user-images.githubusercontent.com/22676175/73603225-d94a9a00-45ba-11ea-8a32-ae15fe6a37ec.png)

**Comment by m1nt07** [comment]
> 1. alpha通道突变时将范围限定为0-64，较低的透明度保证了更多的三角形对最终适应度有影响。
> 2. 坐标和颜色分开突变（不同时突变），解耦后有更大概率突变出优秀基因。
> 3. 三个顶点坐标解耦，横纵坐标解耦，RGBA颜色分量解耦，进一步提高突变出优秀基因的概率。
> 4. 以比颜色突变概率更大一些（2~3倍）的概率突变坐标，能更快收敛。
> 
> 下图是我基于改进的代码用chrome图标迭代15000代后的结果，看起来比您的结果要好一些。
> ![第15000代最优扇贝](https://user-images.githubusercontent.com/22676175/73603207-9dafd000-45ba-11ea-8d56-591e5c4c76c1.png)

这个效果真不错，跟科学松鼠会上介绍的结果差不多。我终于知道自己代码哪里有问题了，谢谢你的意见。
